### ISSUE TITLE
 [Error: Object #<Object> has no method 'formatE164']

### ISSUE THREAD

**Issue by jeremyhodges** [DispatchMe/phoneformat.js#14]
Able to call from the client, but I get `[Error: Object #<Object> has no method 'formatE164']` when I try to call from a Meteor method server-side. Any suggestions?

**Comment by rico** [comment]
I have the same problem. Is it just a client side package?

**Comment by jeremyhodges** [comment]
@rico Yes, it is.

**Comment by rico** [comment]
@jeremyhodges - thanks, then I can't use it :-)

**Comment by jayjo7** [comment]
Hello,

I upgraded an working app to  Meteor to 1,2.0 and phoneformat.js to 1.5.5, after that i am getting the below error message? Any know issue? Any fix in the works? any help would be greatly helpful.

W20150927-18:25:54.961(-7)? (STDERR)
W20150927-18:25:54.962(-7)? (STDERR) /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:283
W20150927-18:25:54.962(-7)? (STDERR) }).run();
W20150927-18:25:54.962(-7)? (STDERR)    ^
W20150927-18:25:54.962(-7)? (STDERR) TypeError: Object #<Object> has no method 'methods'
W20150927-18:25:54.963(-7)? (STDERR)     at Package (packages/dispatch_phoneformat.js/server.js:1:1)
W20150927-18:25:54.963(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/packages/dispatch_phoneformat.js.js:56:4
W20150927-18:25:54.963(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/packages/dispatch_phoneformat.js.js:66:3
W20150927-18:25:54.963(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:242:10
W20150927-18:25:54.963(-7)? (STDERR)     at Array.forEach (native)
W20150927-18:25:54.963(-7)? (STDERR)     at Function._.each._.forEach (/Users/jmounagu/.meteor/packages/meteor-tool/.1.1.8.fsnm9t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150927-18:25:54.963(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20150927-18:25:58.809(-7)? (STDERR)
W20150927-18:25:58.810(-7)? (STDERR) /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:283
W20150927-18:25:58.810(-7)? (STDERR) }).run();
W20150927-18:25:58.810(-7)? (STDERR)    ^
W20150927-18:25:58.812(-7)? (STDERR) TypeError: Object #<Object> has no method 'methods'
W20150927-18:25:58.812(-7)? (STDERR)     at Package (packages/dispatch_phoneformat.js/server.js:1:1)
W20150927-18:25:58.812(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/packages/dispatch_phoneformat.js.js:56:4
W20150927-18:25:58.813(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/packages/dispatch_phoneformat.js.js:66:3
W20150927-18:25:58.813(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:242:10
W20150927-18:25:58.813(-7)? (STDERR)     at Array.forEach (native)
W20150927-18:25:58.813(-7)? (STDERR)     at Function._.each._.forEach (/Users/jmounagu/.meteor/packages/meteor-tool/.1.1.8.fsnm9t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150927-18:25:58.813(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20150927-18:26:02.539(-7)? (STDERR)
W20150927-18:26:02.539(-7)? (STDERR) /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:283
W20150927-18:26:02.540(-7)? (STDERR) }).run();
W20150927-18:26:02.540(-7)? (STDERR)    ^
W20150927-18:26:02.542(-7)? (STDERR) TypeError: Object #<Object> has no method 'methods'
W20150927-18:26:02.542(-7)? (STDERR)     at Package (packages/dispatch_phoneformat.js/server.js:1:1)
W20150927-18:26:02.542(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/packages/dispatch_phoneformat.js.js:56:4
W20150927-18:26:02.542(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/packages/dispatch_phoneformat.js.js:66:3
W20150927-18:26:02.542(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:242:10
W20150927-18:26:02.542(-7)? (STDERR)     at Array.forEach (native)
W20150927-18:26:02.542(-7)? (STDERR)     at Function._.each._.forEach (/Users/jmounagu/.meteor/packages/meteor-tool/.1.1.8.fsnm9t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150927-18:26:02.542(-7)? (STDERR)     at /Users/jmounagu/Documents/workarea/projects/meteor/madrasdosacorner-dev/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by chenrozenes** [comment]
Can you make it a server package as well? I want to use your package, but I need it on the client and on the server as well

**Comment by gregory** [comment]
that would be awesome.
